#!/usr/bin/env bash
#
# Cuenta gatos semanalmente del registro posicion trampas de Socorro
file_list=$(ls *.csv)
zone=${1}
mkdir filtred_data
for file in ${file_list}; do
  echo "Filtrando el archivo ${file}"
    table_name=$(basename "${file}" .csv)
    csvsql --snifflimit 0 --no-inference --blanks --query "
    SELECT *
    FROM ${table_name}
    WHERE Zona = '${zone}'
    " ${file} > ./filtred_data/${table_name}_filtered.csv
done



