#!/usr/bin/env bash
#
# Función que cuenta el esfuerzo o Capturas por día y lo agrupa por zona.
# ./src/get_effort_by_zone [FILE] [ARGUMENTO]
# El argumento puede ser 'Esfuerzo' o 'Capturas'
for fecha in Fecha_1 Fecha_2 Fecha_3 Fecha_4 Fecha_5 Fecha_6 Fecha_7; do
  file_name=${1}
  effort_or_captures=${2}
  [ "$effort_or_captures" == Esfuerzo ] && conditional="${fecha} = 'X' OR ${fecha} = 'A'"
  [ "$effort_or_captures" == Capturas ] && conditional="${fecha} = 'X'"
  
  table_name=$(basename "${file_name}" .csv)
  csvsql --snifflimit 0 --no-inference --blanks --query \
  "SELECT
  '${fecha}' AS Fecha,
    CASE 
      WHEN ID = 'NA' THEN 'NA'
      WHEN ID = 'SM4-Melpo' THEN '01'
      ELSE SUBSTR(ID,4,2)
    END Zona,
    COUNT(*) AS '${effort_or_captures}'
  FROM ${table_name}
  WHERE ${conditional}
  GROUP BY Zona
  " ${file_name}
done
