#!/usr/bin/env bash
#
# Query que clasifica las trampas del archivo posición trampas por zona
for zone in 01 02 03 04 05 06 07 08; do
  data_file=${1}
  table_name=$(basename "${data_file}" .csv)
  csvsql --snifflimit 0 --no-inference --blanks --query "
    SELECT *
    FROM ${table_name}
    WHERE SUBSTR(ID,4,2) = '${zone}'
  " ${data_file} > ${table_name}_zone${zone}.csv
done
./src/remove_empty_files