#!/usr/bin/env bash
#
# Elimina archivos CSV que solo tienen el encabezado y no tienen datos
file_list=$(ls *.csv)
lines=1
for file in ${file_list}; do
  if [ "$(< "${file}" wc -l)" -eq "${lines}" ]; then
    echo -e "El archivo ${file} está vacio"
    rm ${file}
  fi
done
