#!/usr/bin/env bash
#
# Cuenta gatos semanalmente del registro posicion trampas de Socorro
file_list=$(ls *.csv)
for file in ${file_list}; do
  echo "Procesando el archivo ${file}"
  ./cuenta_gatos ${file} | ./transpon_esfuerzo_captura >> resumen_semanal.csv
done
#
# Cuenta el total de noches trampa y el total de capturas
csvsql --no-header-row --query "
  SELECT SUM(a) AS Total_noches_trampa, SUM(b) AS Total_capturas
  FROM resumen_semanal
" resumen_semanal.csv
rm resumen_semanal.csv
