#!/usr/bin/env python
#
# utm2geographical calcula coordendas geográficas a partir de la 

from cli_paths import path_files

import pandas as pd
import utm

paths = path_files()

data_path = paths.input[0][0]
utm_zone = paths.input[1][0]
output_table = paths.output[0][0]

data = pd.read_csv(data_path)

latitude = []
longitude = []

for x, y in zip(data.Coordenada_Este, data.Coordenada_Norte):
    if (x == np.nan) or (y == np.nan):
        latitude.append(np.nan)
        longitude.append(np.nan)  
    else:
        lat, lon = utm.to_latlon(x, y, int(utm_zone[:-1]), utm_zone[-1])
        latitude.append(lat)
        longitude.append(lon)
data["Latitud"] = latitude
data["Longitud"] = longitude
data.to_csv(output_table, index=False)