#!/usr/bin/env bash
#
# Query que une las tablas de esfuerzo y captura en una sola. Hace la unión con la tabla de fechas reales.
effort_name_file=${1}
captures_name_file=${2}
real_and_tmp_dates_file=${3}
effort_table=$(basename "${effort_name_file}" .csv)
captures_table=$(basename "${captures_name_file}" .csv)
real_and_tmp_dates_table=$(basename "${real_and_tmp_dates_file}" .csv)

csvsql --snifflimit 0 --no-inference --blanks --query "
SELECT 
d.real_date AS Fecha,
jt.Zona, jt.Esfuerzo,
  CASE
    WHEN jt.Capturas IS NULL THEN '0' ELSE Capturas
  END Capturas
FROM
  (SELECT
    e.Fecha AS tmp_Fecha,
    e.Zona,
    e.Esfuerzo,
    c.Capturas
  FROM ${effort_table} AS e
  LEFT OUTER JOIN ${captures_table} AS c
  ON e.Fecha = c.Fecha AND e.Zona = c.Zona) AS jt
INNER JOIN ${real_and_tmp_dates_table} AS d
ON d.tmp_date = jt.tmp_Fecha
" ${effort_name_file} ${captures_name_file} ${real_and_tmp_dates_file}
